// <auto-generated />
using System;
using LawyerAssistant.Persistance.ApplicationDbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LawyerAssistant.Persistance.Migrations
{
    [DbContext(typeof(MainDBContext))]
    [Migration("20250521070832_AddReActionTable")]
    partial class AddReActionTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Aggregates.Identities.CustomersModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("LegalCompanyId")
                        .HasColumnType("int");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<DateTime?>("ModDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("NationalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("LegalCompanyId");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Identities.UsersModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Gender")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PicPath")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("RegDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Admin",
                            Gender = true,
                            LastName = "User",
                            PasswordHash = "JfnnlDI7RTiF9RgfG2JNCw==",
                            PicPath = "",
                            RegDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 1,
                            Status = 1,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("LawyerAssistant.Domain.Aggregates.BasicDefinitionsModels.ActionTypesModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ModDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("RememberTime")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("ActionTypes", (string)null);
                });

            modelBuilder.Entity("LawyerAssistant.Domain.Aggregates.BasicDefinitionsModels.BranchesModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ComplexId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("ComplexId");

                    b.ToTable("Branches", (string)null);
                });

            modelBuilder.Entity("LawyerAssistant.Domain.Aggregates.BasicDefinitionsModels.CitiesModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Cities", (string)null);
                });

            modelBuilder.Entity("LawyerAssistant.Domain.Aggregates.BasicDefinitionsModels.ComplexesModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Complexes", (string)null);
                });

            modelBuilder.Entity("LawyerAssistant.Domain.Aggregates.BasicDefinitionsModels.DemandsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FileTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModDateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("RegDateTime")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("FileTypeId");

                    b.ToTable("Demands", (string)null);
                });

            modelBuilder.Entity("LawyerAssistant.Domain.Aggregates.BasicDefinitionsModels.FilesTypesModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ModDateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("RegDateTime")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("FilesTypes", (string)null);
                });

            modelBuilder.Entity("LawyerAssistant.Domain.Aggregates.BasicDefinitionsModels.ProvincesModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Provinces", (string)null);
                });

            modelBuilder.Entity("LawyerAssistant.Domain.Aggregates.IdentitiesModels.LegalCustomersModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LegalNationalCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ModDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RegDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("LegalCustomers", (string)null);
                });

            modelBuilder.Entity("LawyerAssistant.Domain.Aggregates.ReActionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<int?>("BranchesModelId")
                        .HasColumnType("int");

                    b.Property<int?>("ComplexeId")
                        .HasColumnType("int");

                    b.Property<int?>("ComplexesModelId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int?>("CustomersModelId")
                        .HasColumnType("int");

                    b.Property<int>("FileTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("FilesTypesModelId")
                        .HasColumnType("int");

                    b.Property<bool>("GoingToBranch")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModDateTime")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("RegDateTime")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("Time")
                        .HasColumnType("datetime");

                    b.Property<bool>("TimeIsImportant")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("BranchesModelId");

                    b.HasIndex("ComplexeId");

                    b.HasIndex("ComplexesModelId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("CustomersModelId");

                    b.HasIndex("FileTypeId");

                    b.HasIndex("FilesTypesModelId");

                    b.ToTable("ReActions", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Identities.CustomersModel", b =>
                {
                    b.HasOne("LawyerAssistant.Domain.Aggregates.BasicDefinitionsModels.CitiesModel", "City")
                        .WithMany("Customers")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LawyerAssistant.Domain.Aggregates.IdentitiesModels.LegalCustomersModel", "Legal")
                        .WithMany("CompanyCustomers")
                        .HasForeignKey("LegalCompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LawyerAssistant.Domain.Aggregates.BasicDefinitionsModels.ProvincesModel", "Province")
                        .WithMany("Customers")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("City");

                    b.Navigation("Legal");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("LawyerAssistant.Domain.Aggregates.BasicDefinitionsModels.BranchesModel", b =>
                {
                    b.HasOne("LawyerAssistant.Domain.Aggregates.BasicDefinitionsModels.ComplexesModel", "Complexe")
                        .WithMany("Branches")
                        .HasForeignKey("ComplexId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Complexe");
                });

            modelBuilder.Entity("LawyerAssistant.Domain.Aggregates.BasicDefinitionsModels.CitiesModel", b =>
                {
                    b.HasOne("LawyerAssistant.Domain.Aggregates.BasicDefinitionsModels.ProvincesModel", "Province")
                        .WithMany("Cities")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("LawyerAssistant.Domain.Aggregates.BasicDefinitionsModels.ComplexesModel", b =>
                {
                    b.HasOne("LawyerAssistant.Domain.Aggregates.BasicDefinitionsModels.CitiesModel", "City")
                        .WithMany("Complexes")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("LawyerAssistant.Domain.Aggregates.BasicDefinitionsModels.DemandsModel", b =>
                {
                    b.HasOne("LawyerAssistant.Domain.Aggregates.BasicDefinitionsModels.FilesTypesModel", "FilesType")
                        .WithMany("Demands")
                        .HasForeignKey("FileTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FilesType");
                });

            modelBuilder.Entity("LawyerAssistant.Domain.Aggregates.ReActionModel", b =>
                {
                    b.HasOne("LawyerAssistant.Domain.Aggregates.BasicDefinitionsModels.BranchesModel", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LawyerAssistant.Domain.Aggregates.BasicDefinitionsModels.BranchesModel", null)
                        .WithMany("Reactions")
                        .HasForeignKey("BranchesModelId");

                    b.HasOne("LawyerAssistant.Domain.Aggregates.BasicDefinitionsModels.ComplexesModel", "Complexe")
                        .WithMany()
                        .HasForeignKey("ComplexeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LawyerAssistant.Domain.Aggregates.BasicDefinitionsModels.ComplexesModel", null)
                        .WithMany("Reactions")
                        .HasForeignKey("ComplexesModelId");

                    b.HasOne("Domain.Aggregates.Identities.CustomersModel", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Aggregates.Identities.CustomersModel", null)
                        .WithMany("Reactions")
                        .HasForeignKey("CustomersModelId");

                    b.HasOne("LawyerAssistant.Domain.Aggregates.BasicDefinitionsModels.FilesTypesModel", "FilesTypes")
                        .WithMany()
                        .HasForeignKey("FileTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LawyerAssistant.Domain.Aggregates.BasicDefinitionsModels.FilesTypesModel", null)
                        .WithMany("Reactions")
                        .HasForeignKey("FilesTypesModelId");

                    b.Navigation("Branch");

                    b.Navigation("Complexe");

                    b.Navigation("Customer");

                    b.Navigation("FilesTypes");
                });

            modelBuilder.Entity("Domain.Aggregates.Identities.CustomersModel", b =>
                {
                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("LawyerAssistant.Domain.Aggregates.BasicDefinitionsModels.BranchesModel", b =>
                {
                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("LawyerAssistant.Domain.Aggregates.BasicDefinitionsModels.CitiesModel", b =>
                {
                    b.Navigation("Complexes");

                    b.Navigation("Customers");
                });

            modelBuilder.Entity("LawyerAssistant.Domain.Aggregates.BasicDefinitionsModels.ComplexesModel", b =>
                {
                    b.Navigation("Branches");

                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("LawyerAssistant.Domain.Aggregates.BasicDefinitionsModels.FilesTypesModel", b =>
                {
                    b.Navigation("Demands");

                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("LawyerAssistant.Domain.Aggregates.BasicDefinitionsModels.ProvincesModel", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("Customers");
                });

            modelBuilder.Entity("LawyerAssistant.Domain.Aggregates.IdentitiesModels.LegalCustomersModel", b =>
                {
                    b.Navigation("CompanyCustomers");
                });
#pragma warning restore 612, 618
        }
    }
}
