// <auto-generated />
using System;
using LawyerAssistant.Persistance.ApplicationDbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LawyerAssistant.Persistance.Migrations
{
    [DbContext(typeof(MainDBContext))]
    partial class MainDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LawyerAssistant.Domain.Aggregates.BasicDefinitionsModels.CitiesModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModDateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<int?>("ProvincesModelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegDateTime")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("ProvincesModelId");

                    b.ToTable("Cities", (string)null);
                });

            modelBuilder.Entity("LawyerAssistant.Domain.Aggregates.BasicDefinitionsModels.DemandsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FileId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModDateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("RegDateTime")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.ToTable("Demands", (string)null);
                });

            modelBuilder.Entity("LawyerAssistant.Domain.Aggregates.BasicDefinitionsModels.FilesTypesModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ModDateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("RegDateTime")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("FilesTypes", (string)null);
                });

            modelBuilder.Entity("LawyerAssistant.Domain.Aggregates.BasicDefinitionsModels.ProvincesModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModDateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("RegDateTime")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("Provinces", (string)null);
                });

            modelBuilder.Entity("LawyerAssistant.Domain.Aggregates.BasicDefinitionsModels.CitiesModel", b =>
                {
                    b.HasOne("LawyerAssistant.Domain.Aggregates.BasicDefinitionsModels.ProvincesModel", null)
                        .WithMany("Cities")
                        .HasForeignKey("ProvincesModelId");
                });

            modelBuilder.Entity("LawyerAssistant.Domain.Aggregates.BasicDefinitionsModels.DemandsModel", b =>
                {
                    b.HasOne("LawyerAssistant.Domain.Aggregates.BasicDefinitionsModels.FilesTypesModel", "FilesType")
                        .WithMany("Demands")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FilesType");
                });

            modelBuilder.Entity("LawyerAssistant.Domain.Aggregates.BasicDefinitionsModels.FilesTypesModel", b =>
                {
                    b.Navigation("Demands");
                });

            modelBuilder.Entity("LawyerAssistant.Domain.Aggregates.BasicDefinitionsModels.ProvincesModel", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
